site_name: KubeCI - Kubernetes Continuous Integration and Delivery
pages:
  - KubeCI Overview: index.md
  - Architecture: architecture.md
  - Jobs:
    - Overview: jobs/index.md
    - Rules: jobs/rules.md
    - Steps: jobs/steps.md
    - Notifiers: jobs/notifiers.md
  - Endpoints:
    - Overview: endpoints/index.md
    - Trigger Jobs: endpoints/trigger-jobs.md
    - Job Callback: endpoints/job-callback.md
    - Healthz: endpoints/healthz.md
    - Metrics: endpoints/metrics.md
    - Execute Job: endpoints/execute-job.md
    - Notify: endpoints/notify.md
  - Todo: todo.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
