site_name: KubeCI - Kubernetes Continuous Integration and Delivery
pages:
  - KubeCI Overview: index.md
  - Architecture: architecture.md
  - Jobs:
    - Overview: jobs/index.md
    - Rules: jobs/rules.md
    - Steps: jobs/steps.md
    - Notifiers: jobs/notifiers.md
  - Endpoints:
    - External:
      - Overview: endpoints/external/index.md
      - Healthz: endpoints/external/healthz.md
      - Inbound Webhook: endpoints/external/inbound-webhook.md
      - Job Callback: endpoints/external/job-callback.md
      - Metrics: endpoints/external/metrics.md
    - Internal:
      - Overview: endpoints/internal/index.md
      - Execute Job: endpoints/internal/execute-job.md
      - Notify: endpoints/internal/notify.md
  - Todo: todo.md
theme: material
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
